FROM mdillon/postgis:9.6

ENV BACKUP_HOME=/opt/backup

WORKDIR $BACKUP_HOME

USER root

RUN apt update -y && \
    apt install -y awscli mcrypt && \
    mkdir -p $BACKUP_HOME && \ 
    deluser backup && \
    useradd -ms /bin/bash backup

COPY ./do_backup.sh $BACKUP_HOME

RUN chown -R backup:root $BACKUP_HOME && \
    chmod +x $BACKUP_HOME/do_backup.sh && \
    chmod g+rw $BACKUP_HOME

USER backup
