apiVersion: batch/v1
kind: Job
metadata:
  name: landmarks-db-backup
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: landmarks-db-backup
    spec:
      activeDeadlineSeconds: 1800
      restartPolicy: OnFailure
      containers:
          - name: backup-maker
            image: quay.io/jstakun/pg-backup:0.3
            envFrom:
            - configMapRef:
                name: pg-backup-conf
            args:
            - /bin/bash
            - /opt/backup/do_backup.sh
            env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: landmarksdb
                  key: database-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: landmarksdb
                  key: database-user
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_SECRET_ACCESS_KEY
